### ISSUE TITLE
structuremap dependency with package id being lowercase

### ISSUE THREAD

**Issue by delepster** [structuremap/StructureMap.Microsoft.DependencyInjection#16]
Since 4.3.0, structuremap's package is camel-cased, i.e. StructureMap vs structuremap. Now I have an .net core mvc api which depends on StructureMap.Microsoft.DependencyInjection and another (private) nuget package which latter depends on StructureMap.

When the dependencies are resolved, I end up with two structuremap assemblies, coming from the camel-case package and the lowercase package and this makes IServiceCollection.AddMvc() to crash wen trying to add assembly names (?) in its internal dictionary.

I am not sure how to fix this and how StructureMap.Microsoft.DependencyInjection ended up depending on the lowercase package.

**Comment by khellang** [comment]
See https://github.com/structuremap/StructureMap.Microsoft.DependencyInjection/issues/14

**Comment by khellang** [comment]
> Since 4.3.0, structuremap's package is camel-cased, i.e. StructureMap vs structuremap.

That's not the case. You can't change a NuGet package's ID. It *is* and has always been `structuremap` (lowercase). When @jeremydmiller changed to the dotnet CLI, it automatically used the project name for the NuGet package title, which is `StructureMap`. As mentioned in #14, the title is purely for tooling and should not be used anywhere for dependencies.

> I am not sure how to fix this

You should be able to fix it by pinning the structuremap package (i.e. explicitly adding the package to your project.json). Otherwise you just have to wait for NuGet to fix its bugs 😛 

> and how StructureMap.Microsoft.DependencyInjection ended up depending on the lowercase package.

As I said; it's always been lowercase :smile:

**Comment by delepster** [comment]
Thanks for the info, but I already tried and retried it again with no luck. The project depending on the camelcase version is a .net 4.6 project which uses a packages.config (vs a project.json file) and even if I am changing the id manually, I end up with a camelcase id for structureamp in the dependency list.

**Comment by khellang** [comment]
Try downloading the RC of NuGet 3.5 and see if that helps you... https://dist.nuget.org/index.html

**Comment by KFR42** [comment]
Is there a workaround for this?  The newest RC for NuGet does not address this issue.

Specifically, I have a core class library package that uses structuremap which I have created myself and a separate web project in another solution which brings that in as well as StructureMap.Microsoft.DependencyInjection which results in the clash.  I have tried installing via the lowercase titled version of the StructureMap package, which also makes no difference.

**Comment by khellang** [comment]
I don't know. There's little I can do. This is a NuGet issue :cry:

**Comment by KFR42** [comment]
I just thought maybe one of the users here had come up with something given this basically makes structuremap unusable in certain situations.  Is there anything that's been raised with NuGet that I can get behind as currently our project cannot continue.

**Comment by khellang** [comment]
I think so, but they've all been closed as far as I can see; https://github.com/NuGet/Home/issues/2939, https://github.com/NuGet/Home/issues/2901.

@emgarten, @joelverhagen @yishaigalatzer @blackdwarf You're all involved in the NuGet issues linked. Can you confirm that this issue is fixed in the latest RC of NuGet? Is there anything we can do to get around this?

**Comment by yishaigalatzer** [comment]
The issue is fixed in dotnet preview 3 and  nuget 3.6rc

**Comment by khellang** [comment]
Thanks @yishaigalatzer :smile:
